Repository starship/starship, pull requests merged in 2019-08, with the labels that each got.

#118 feat: implement timer module
  docs/config/README.md
  src/init.rs
  src/main.rs
  src/modules/cmd_duration.rs
  src/modules/mod.rs
  src/print.rs
  tests/testsuite/cmd_duration.rs
  tests/testsuite/main.rs
Labels: ✨ enhancement

#136 Update installation docs
  README.md
Labels: 🔧 maintenance

#139 fix: Move the battery to the newline before character
  src/print.rs
Labels: 🔧 maintenance

#85 feat: Implement the prompt module for jobs
  README.md
  docs/config/README.md
  src/init.rs
  src/main.rs
  src/modules/jobs.rs
  src/modules/mod.rs
  src/print.rs
  tests/testsuite/jobs.rs
  tests/testsuite/main.rs
Labels: ✨ enhancement

#140 feat: Implement Python version from pyenv
  ci/setup-test-env.yml
  docs/config/README.md
  src/modules/python.rs
  tests/testsuite/python.rs
Labels: ✨ enhancement

#143 ci: Automate the bumping of the starship Brew formula
  azure-pipelines.yml
  ci/bump-brew-formula.yml
  ci/install-cross-rust.yml
Labels: 🔧 maintenance

#146 fix: Give all modules a single name
  src/modules/golang.rs
  src/modules/mod.rs
  src/modules/nodejs.rs
  tests/testsuite/cmd_duration.rs
  tests/testsuite/directory.rs
  tests/testsuite/golang.rs
  tests/testsuite/nodejs.rs
Labels: 🐛 bug

#131 feat: implement the ruby module
  README.md
  ci/setup-test-env.yml
  docs/config/README.md
  src/modules/mod.rs
  src/modules/ruby.rs
  tests/Dockerfile
  tests/testsuite/main.rs
  tests/testsuite/ruby.rs
Labels: ✨ enhancement

#176 docs: Small doc touch-ups
  README.md
  docs/config/README.md
Labels: 🔧 maintenance

#184 docs: Update setup instructions on landing page
  docs/README.md
Labels: 🔧 maintenance

#200 chore(deps): Update `crossbeam-epoch` dependency
  Cargo.lock
Labels: 🔧 maintenance

#262 docs: Add undocumented config options
  docs/config/README.md
Labels: 🔧 maintenance
