Repository starship/starship, pull requests merged in 2019-05, with the labels that each got.

#42 Add a code of conduct to the project
  CODE_OF_CONDUCT.md
Labels: maintenance

#64 fix: Don't check extensions of directories
  src/context.rs
Labels: optimization

#63 feat: Add battery module
  Cargo.lock
  Cargo.toml
  README.md
  src/main.rs
  src/modules/battery.rs
  src/modules/mod.rs
  src/print.rs
Labels: enhancement

#65 Add starship logo to README.md
  README.md
  media/logo.png
  media/logo.svg
  svg/comet.svg
  svg/galaxy.svg
Labels: maintenance

#70 Use starship-test docker image for running integration tests
  azure-pipelines.yml
  ci/azure-test-docker.yml
  integration_test
Labels: maintenance

#68 Use tarpaulin and Codecov for adding code coverage to project
  .gitignore
  README.md
  ci/azure-test-docker.yml
  integration_test
  tests/Dockerfile
Labels: maintenance
